# Generated by Django 3.1.1 on 2020-10-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TBGR',
            fields=[
                ('board', models.CharField(max_length=20)),
                ('village', models.CharField(max_length=20)),
                ('tbgrno', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
    ]
