# Generated by Django 3.1.1 on 2020-10-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tobacco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbgr',
            name='name',
            field=models.CharField(default='prudhvi', max_length=50),
            preserve_default=False,
        ),
    ]
