# Generated by Django 3.1.1 on 2020-10-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tobacco', '0004_auto_20201017_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='boardid',
            field=models.AutoField(auto_created=True, max_length=5, primary_key=True, serialize=False),
        ),
    ]
