# Generated by Django 3.1.1 on 2020-10-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tobacco', '0005_auto_20201017_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='boardid',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='village',
            name='villageid',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
