# Generated by Django 3.1.1 on 2020-10-17 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tobacco', '0006_auto_20201017_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='village',
            old_name='boardid',
            new_name='boardname',
        ),
    ]
