# Generated by Django 3.1.1 on 2020-10-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tobacco', '0008_auto_20201017_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('tbgrno', models.CharField(max_length=20)),
                ('grade', models.CharField(max_length=5)),
                ('lotno', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('weight', models.IntegerField(max_length=5)),
                ('height', models.IntegerField(max_length=5)),
            ],
        ),
    ]
