# Generated by Django 3.1.1 on 2020-10-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tobacco', '0009_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
