# Generated by Django 3.1.1 on 2020-10-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tobacco', '0011_auto_20201017_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('gradeid', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.CharField(max_length=5)),
            ],
        ),
    ]
