# Generated by Django 3.1.1 on 2020-11-02 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tobacco', '0013_auto_20201018_1244'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Card',
            new_name='Slip',
        ),
    ]
