# Generated by Django 3.1.1 on 2020-11-02 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tobacco', '0014_auto_20201102_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='slip',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 2, 15, 55, 47, 463123)),
        ),
    ]
