# Generated by Django 3.1.1 on 2020-11-02 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tobacco', '0015_slip_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slip',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 11, 2, 16, 13, 29, 210837)),
        ),
    ]
