# Generated by Django 3.1.1 on 2020-11-02 10:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tobacco', '0016_auto_20201102_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slip',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 11, 2, 10, 47, 1, 641426, tzinfo=utc)),
        ),
    ]
