# Generated by Django 3.1.1 on 2020-11-02 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tobacco', '0017_auto_20201102_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slip',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 11, 2, 16, 18, 49, 549584)),
        ),
    ]
