# Generated by Django 3.1.1 on 2020-11-02 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tobacco', '0018_auto_20201102_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slip',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 2, 16, 19, 59, 631444)),
        ),
    ]
