# Generated by Django 3.1.1 on 2020-11-03 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tobacco', '0019_auto_20201102_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='slip',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 13, 24, 21, 551561)),
        ),
    ]
